name: Postman Test Automation

on:
  push:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Postman CLI
        run: npm install -g @postman/cli
      - name: Authenticate with Postman
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run Postman Monitor
        run: postman monitor run <monitor_uid>
